<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'Support\\' => array($baseDir . '/Support'),
    'Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'Libs\\' => array($baseDir . '/Libs'),
    'Carbon\\' => array($vendorDir . '/nesbot/carbon/src/Carbon'),
);
